# Generated by Django 3.0.7 on 2020-07-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('objective', models.CharField(max_length=1000)),
                ('categories', models.CharField(default='None', max_length=1000)),
                ('expected_completion_date', models.CharField(default='Season, Year', max_length=200)),
                ('description', models.TextField()),
                ('contributing_nations', models.CharField(max_length=1000)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
