# Generated by Django 3.0.7 on 2020-07-29 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
