# Generated by Django 3.0.7 on 2020-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_focuslog_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslog',
            name='about_bird',
            field=models.TextField(default='None'),
        ),
    ]
