# Generated by Django 3.0.7 on 2020-08-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_focuslog_about_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslog',
            name='focus_image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
