# Generated by Django 3.0.7 on 2020-08-26 19:28

from django.db import migrations, models
import focus.models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_focuslog_focus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuslog',
            name='focus_image',
            field=models.ImageField(blank=True, upload_to=focus.models.get_image_filename),
        ),
    ]
