# Generated by Django 3.0.7 on 2020-08-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_auto_20200826_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuslog',
            name='focus_image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
