# Generated by Django 3.0.7 on 2020-10-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_auto_20200826_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuslog',
            name='url',
            field=models.TextField(default='None'),
        ),
    ]
