# Generated by Django 4.2.2 on 2023-08-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ticket_number', models.CharField(max_length=100)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('additional_notes', models.CharField(max_length=100)),
            ],
        ),
    ]
