# Generated by Django 4.2.2 on 2023-08-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate_contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='compensation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ticket_number',
            field=models.CharField(max_length=100),
        ),
    ]
