# Generated by Django 4.2.2 on 2023-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate_contract', '0002_alter_contract_compensation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
