# Generated by Django 4.2.2 on 2023-08-07 18:51

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('introduction', tinymce.models.HTMLField()),
                ('try_it', tinymce.models.HTMLField()),
                ('create_it', tinymce.models.HTMLField()),
                ('completed', models.BooleanField(default=True)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.subset')),
            ],
        ),
    ]
