# Generated by Django 4.2.2 on 2023-08-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
