# Generated by Django 3.0.7 on 2023-06-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Subset'),
        ),
    ]
