# Generated by Django 4.2.2 on 2023-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
