# Generated by Django 3.0.7 on 2023-06-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20230626_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='create_it',
        ),
    ]
