# Generated by Django 3.0.7 on 2023-06-26 16:50

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20230626_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='try_it',
        ),
        migrations.AddField(
            model_name='lesson',
            name='try_it',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
